name: Publish on Docker CI

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get the version
              id: get_version
              run: |
                  if [[ $GITHUB_REF == refs/tags/* ]]; then
                    echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
                  else
                    echo ::set-output name=VERSION::latest
                  fi
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: |
                      testadirapa/homunculus-desk:${{ steps.get_version.outputs.VERSION }}
                      testadirapa/homunculus-desk:latest
